[versions]
neoforged-moddev = "2.0.42-beta"
kotlinforforge = "5.6.0"

[libraries]
kotlinforforge = { module="thedarkcolour:kotlinforforge-neoforge", version.ref="kotlinforforge" }

[plugins]
neoforged-moddev = { id="net.neoforged.moddev", version.ref="neoforged-moddev" }